In [27]:
%run ../notebook/notebook_setup.py
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
from config.config import X_TRAIN, X_TEST, Y_TRAIN, Y_TEST

In [28]:
X_train = joblib.load(X_TRAIN)
X_test = joblib.load(X_TEST)
y_train = joblib.load(Y_TRAIN)
y_test = joblib.load(Y_TEST)

In [29]:
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_test_flat = X_test.reshape(X_test.shape[0], -1)

In [4]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression

log = LogisticRegression()

log.fit(X_train_flat, y_train)

/home/inventor/Speech Emotion Recognition/speechemotion/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [5]:
y_pred_log = log.predict(X_test_flat)

In [6]:
y_test

array([4, 6, 1, 4, 2, 6, 0, 4, 1, 1, 2, 5, 4, 7, 3, 1, 6, 1, 0, 4, 6, 2,
       0, 7, 3, 2, 3, 0, 5, 2, 7, 4, 2, 6, 1, 7, 5, 1, 4, 6, 0, 6, 0, 2,
       1, 7, 0, 4, 1, 3, 1, 2, 7, 3, 0, 1, 4, 3, 6, 4, 2, 6, 3, 6, 4, 2,
       4, 2, 2, 6, 1, 4, 2, 4, 2, 4, 7, 6, 0, 0, 7, 1, 7, 2, 5, 0, 7, 0,
       3, 1, 1, 4, 3, 1, 4, 7, 1, 6, 4, 6, 6, 4, 2, 7, 6, 3, 5, 5, 2, 2,
       4, 5, 0, 0, 4, 1, 0, 0, 0, 6, 3, 2, 0, 3, 0, 2, 2, 2, 0, 6, 1, 7,
       6, 6, 3, 6, 2, 1, 1, 0, 4, 7, 5, 2, 4, 3, 1, 5, 7, 2, 0, 4, 6, 4,
       0, 1, 3, 2, 2, 2, 0, 4, 6, 3, 3, 2, 0, 7, 6, 7, 2, 0, 6, 5, 2, 4,
       6, 1, 6, 1, 3, 3, 2, 3, 5, 4, 1, 6, 7, 1, 1, 2, 2, 0, 0, 3, 4, 6,
       5, 6, 6, 7, 3, 4, 0, 3, 2, 7, 7, 2, 2, 4, 7, 7, 7, 5, 6, 4, 1, 1,
       7, 1, 0, 1, 3, 6, 4, 0, 2, 3, 3, 0, 1, 7, 6, 6, 1, 7, 1, 0, 0, 7,
       2, 4, 6, 6, 7, 0, 1, 7, 3, 0, 3, 7, 4, 3, 6, 5, 4, 0, 5, 4, 5, 2,
       6, 1, 0, 2, 6, 0, 4, 2, 2, 1, 7, 5, 4, 7, 1, 7, 4, 1, 6, 1, 7, 3,
       3, 0, 0, 3, 6, 0, 6, 7, 3, 7, 1, 7, 1, 6, 2,

In [7]:
y_pred_log

array([3, 3, 1, 1, 6, 6, 0, 2, 3, 1, 3, 1, 3, 7, 6, 1, 0, 1, 0, 2, 5, 6,
       0, 7, 7, 6, 4, 2, 5, 6, 7, 4, 2, 6, 1, 7, 5, 3, 4, 0, 0, 4, 6, 4,
       1, 7, 0, 4, 1, 3, 1, 2, 0, 1, 2, 1, 4, 3, 6, 4, 6, 5, 6, 6, 4, 2,
       4, 7, 2, 3, 1, 3, 2, 4, 6, 4, 0, 6, 0, 0, 3, 1, 3, 2, 6, 7, 7, 0,
       3, 1, 1, 3, 3, 1, 4, 5, 6, 6, 4, 3, 6, 4, 2, 7, 2, 2, 1, 5, 2, 2,
       4, 6, 0, 0, 7, 1, 7, 7, 0, 6, 5, 6, 0, 0, 0, 6, 2, 4, 0, 6, 2, 7,
       6, 6, 3, 6, 5, 5, 1, 0, 3, 7, 5, 2, 2, 7, 1, 2, 2, 7, 0, 6, 3, 4,
       4, 1, 3, 2, 2, 2, 0, 7, 6, 6, 4, 1, 3, 7, 0, 4, 2, 7, 6, 5, 1, 2,
       7, 1, 0, 1, 4, 3, 4, 3, 5, 4, 1, 6, 7, 3, 6, 3, 6, 2, 2, 3, 2, 5,
       6, 6, 1, 7, 3, 5, 0, 3, 6, 7, 7, 2, 4, 4, 7, 6, 7, 4, 6, 4, 1, 1,
       7, 5, 1, 1, 3, 3, 4, 4, 6, 3, 7, 0, 6, 1, 0, 6, 1, 7, 1, 3, 0, 6,
       2, 4, 1, 1, 7, 0, 6, 4, 4, 6, 3, 7, 7, 7, 6, 5, 0, 0, 3, 6, 7, 6,
       6, 1, 0, 6, 6, 6, 3, 2, 2, 1, 7, 5, 6, 7, 1, 7, 3, 2, 1, 1, 7, 3,
       3, 2, 1, 4, 7, 0, 1, 7, 6, 7, 6, 7, 1, 6, 2,

In [8]:
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report

y_proba_log = log.predict_proba(X_test_flat)

acc_score_log = accuracy_score(y_test, y_pred_log)
roc_log = roc_auc_score(y_test, y_proba_log, multi_class='ovr')
cr_log = classification_report(y_test, y_pred_log)

In [9]:
print(f"Accuracy Score Logistic Regression: {acc_score_log:.2f}%")
print(f"ROC AUC Score Logistic Regression: {roc_log:.2f}%")
print(f"Classification Report Logistic Regression: \n{cr_log}")

Accuracy Score Logistic Regression: 0.55%
ROC AUC Score Logistic Regression: 0.88%
Classification Report Logistic Regression: 
              precision    recall  f1-score   support

           0       0.69      0.59      0.64        76
           1       0.69      0.66      0.68        77
           2       0.52      0.48      0.50        77
           3       0.56      0.57      0.56        77
           4       0.59      0.49      0.54        77
           5       0.44      0.45      0.44        38
           6       0.35      0.45      0.40        77
           7       0.56      0.61      0.58        77

    accuracy                           0.55       576
   macro avg       0.55      0.54      0.54       576
weighted avg       0.56      0.55      0.55       576



In [30]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier()

forest.fit(X_train_flat, y_train)

y_pred_forest = forest.predict(X_test_flat)
y_proba_forest = forest.predict_proba(X_test_flat)

In [31]:
acc_score_forest = accuracy_score(y_test, y_pred_forest)
roc_forest = roc_auc_score(y_test, y_proba_forest, multi_class='ovr')
cr_forest = classification_report(y_test, y_pred_forest)

In [32]:
print(f"Accuracy Score Forest: {acc_score_forest:.2f}%")
print(f"ROC AUC Score Forest: {roc_forest:.2f}%")
print(f"Classification Report Forest: \n{cr_forest}")

Accuracy Score Forest: 0.87%
ROC AUC Score Forest: 0.99%
Classification Report Forest: 
              precision    recall  f1-score   support

           0       0.89      0.89      0.89        76
           1       0.90      0.95      0.92        77
           2       0.91      0.82      0.86        77
           3       0.80      0.84      0.82        77
           4       0.92      0.84      0.88        77
           5       1.00      1.00      1.00        38
           6       0.77      0.77      0.77        77
           7       0.83      0.90      0.86        77

    accuracy                           0.87       576
   macro avg       0.88      0.88      0.88       576
weighted avg       0.87      0.87      0.87       576



In [13]:
from sklearn.svm import SVC

svc = SVC()

svc.fit(X_train_flat, y_train)

y_pred_svc = svc.predict(X_test_flat)

In [14]:
acc_score_svc = accuracy_score(y_test, y_pred_svc)
# roc_svc = roc_auc_score(y_test, y_pred_svc, multi_class='ovr')
cr_svc = classification_report(y_test, y_pred_svc)

In [15]:
print(f"Accuracy Score SVC: {acc_score_svc:.2f}%")
print(f"Classification Report SVC: \n{cr_svc}")

Accuracy Score SVC: 0.40%
Classification Report SVC: 
              precision    recall  f1-score   support

           0       0.55      0.47      0.51        76
           1       0.37      0.65      0.47        77
           2       0.44      0.39      0.41        77
           3       0.41      0.38      0.39        77
           4       0.44      0.16      0.23        77
           5       0.00      0.00      0.00        38
           6       0.27      0.27      0.27        77
           7       0.38      0.66      0.49        77

    accuracy                           0.40       576
   macro avg       0.36      0.37      0.35       576
weighted avg       0.38      0.40      0.37       576



In [ ]:
from xgboost import XGBClassifier

xgb = XGBClassifier()

xgb.fit(X_train_flat, y_train)

In [14]:
y_pred_xgb = xgb.predict(X_test_flat)
y_proba_xgb = xgb.predict_proba(X_test_flat)

In [15]:
acc_score_xgb = accuracy_score(y_test, y_pred_xgb)
roc_xgb = roc_auc_score(y_test, y_proba_xgb, multi_class='ovr')
cr_xgb = classification_report(y_test, y_pred_xgb)

In [16]:
print(f"Accuracy Score XGB: {acc_score_xgb:.2f}%")
print(f"ROC AUC Score XGB: {roc_xgb:.2f}%")
print(f"Classification Report Xgboost: \n{cr_xgb}")

Accuracy Score XGB: 0.87%
ROC AUC Score XGB: 0.99%
Classification Report Xgboost: 
              precision    recall  f1-score   support

           0       0.92      0.87      0.89        76
           1       0.81      0.90      0.85        77
           2       0.94      0.79      0.86        77
           3       0.90      0.90      0.90        77
           4       0.94      0.87      0.91        77
           5       0.83      1.00      0.90        38
           6       0.77      0.79      0.78        77
           7       0.88      0.92      0.90        77

    accuracy                           0.87       576
   macro avg       0.87      0.88      0.87       576
weighted avg       0.88      0.87      0.87       576



In [17]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier()

tree.fit(X_train_flat,y_train)

DecisionTreeClassifier()

In [18]:
y_pred_tree = tree.predict(X_test_flat)
y_proba_tree = tree.predict_proba(X_test_flat)

In [19]:
acc_score_tree = accuracy_score(y_test, y_pred_tree)
roc_tree = roc_auc_score(y_test, y_proba_tree, multi_class='ovr')
cr_tree = classification_report(y_test, y_pred_tree)

In [20]:
print(f"Accuracy Score Decision Tree: {acc_score_tree:.2f}%")
print(f"ROC AUC Score Decision Tree: {roc_tree:.2f}%")
print(f"Classification Report Decision Tree: \n{cr_tree}")

Accuracy Score Decision Tree: 0.84%
ROC AUC Score Decision Tree: 0.92%
Classification Report Decision Tree: 
              precision    recall  f1-score   support

           0       0.82      0.84      0.83        76
           1       0.94      0.84      0.89        77
           2       0.93      0.71      0.81        77
           3       0.78      0.92      0.85        77
           4       0.83      0.90      0.86        77
           5       0.90      1.00      0.95        38
           6       0.76      0.74      0.75        77
           7       0.85      0.87      0.86        77

    accuracy                           0.84       576
   macro avg       0.85      0.85      0.85       576
weighted avg       0.85      0.84      0.84       576



In [4]:
X_train.shape

(2304, 39, 300)

In [26]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [7]:
device

'cuda'

In [8]:
device = torch.device("cpu")

In [9]:
device

device(type='cpu')

In [10]:
y_train

array([3, 4, 2, ..., 7, 2, 6], shape=(2304,))

In [38]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)

y_train_tensor, y_test_tensor = torch.tensor(y_train, dtype=torch.long), torch.tensor(y_test, dtype=torch.long)

In [39]:
X_train_tensor.shape

torch.Size([2304, 39, 300])

In [40]:
y_train_tensor

tensor([3, 4, 2,  ..., 7, 2, 6])

In [41]:
X_train_tensor = X_train_tensor.unsqueeze(1)
X_test_tensor = X_test_tensor.unsqueeze(1)

In [42]:
X_train_tensor.shape

torch.Size([2304, 1, 39, 300])

In [43]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16)

In [44]:
class EmotionCNN(nn.Module):
    def __init__(self, num_classes=8):
        super().__init__()

        self.conv_layers = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.fc_layers = nn.Sequential(
            nn.Linear(128 * 4 * 37, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
    def forward(self, x):
        x = self.conv_layers(x)
        x = torch.flatten(x, 1)
        x = self.fc_layers(x)

        return x

In [45]:
emotion_cnn_model = EmotionCNN(num_classes=8).to(device)

In [46]:
cross_loss = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(emotion_cnn_model.parameters(), lr=0.001)

In [47]:
# Put the target data on device
X_train_tensor = X_train_tensor.to(device)
X_test_tensor = X_test_tensor.to(device)
y_train_tensor, y_test_tensor = y_train_tensor.to(device), y_test_tensor.to(device)

In [48]:
X_train_tensor.shape

torch.Size([2304, 1, 39, 300])

In [49]:
from sklearn.metrics import accuracy_score

In [50]:
# Evalution of Model

train_loss_value_cnn = []
test_loss_value_cnn = []
train_accuracy_cnn = []
test_accuracy_cnn = []

epoch_counts = []

torch.manual_seed(42)

epochs = 30

for epoch in tqdm(range(epochs), desc="Training CNN Model"):

    # Training phase
    emotion_cnn_model.train()

    total_train_loss = 0
    total_train_correct = 0
    total_train_samples = 0

    # Forward pass
    for X_batch, y_batch in tqdm(train_loader, desc="Training Batches", leave=False):

        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        y_train_logits = emotion_cnn_model(X_batch)
        y_train_pred = torch.argmax(y_train_logits, dim=1)

        # Calculate loss
        train_loss = cross_loss(y_train_logits, y_batch)

        # Calculate accuracy
        train_acc = accuracy_score(y_batch.cpu(), y_train_pred.cpu())

        # Optimzer zero grad
        optimizer.zero_grad()

        # Loss Backward
        train_loss.backward()

        # Optimizer step
        optimizer.step()

        # Accumulate loss
        total_train_loss  += train_loss.item() * X_batch.size(0)
        total_train_correct += (y_train_pred == y_batch).sum().item()
        total_train_samples += X_batch.size(0)

    # Model testing phase

    emotion_cnn_model.eval()
    total_test_loss = 0
    total_test_correct = 0
    total_test_samples = 0

    with torch.inference_mode():
        for X_batch_test, y_batch_test in tqdm(test_loader, desc="Testing Batches" ,leave=False):
            X_batch_test, y_batch_test = X_batch_test.to(device), y_batch_test.to(device)
            test_logits = emotion_cnn_model(X_batch_test)
            test_pred = torch.argmax(test_logits, dim=1)

            # Calculate loss
            test_loss = cross_loss(test_logits, y_batch_test)
            # Calculate accuracy
            test_acc = accuracy_score(y_batch_test.cpu(), test_pred.cpu())

            # Accumulate loss
            total_test_loss += test_loss.item() * X_batch_test.size(0)
            total_test_correct += (test_pred == y_batch_test).sum().item()
            total_test_samples += X_batch_test.size(0)
    
    # Calculate average losses and accuracies
    epoch_train_loss = total_train_loss / total_train_samples
    epoch_test_loss = total_test_loss / total_test_samples

    epoch_train_acc = total_train_correct / total_train_samples * 100
    epoch_test_acc = total_test_correct / total_test_samples * 100

    if epoch % 5 == 0:
        train_loss_value_cnn.append(epoch_train_loss)
        test_loss_value_cnn.append(epoch_test_loss)
        train_accuracy_cnn.append(epoch_train_acc)
        test_accuracy_cnn.append(epoch_test_acc)
        epoch_counts.append(epoch)

        print(f"Epoch: {epoch} | "
              f"Train Loss: {epoch_train_loss:3f} | Train Accuracy: {epoch_train_acc:.2f}% |"
              f"Test Loss: {epoch_test_loss:.3f} | Test Accuracy: {epoch_test_acc:.2f}")


Training CNN Model:   0%|          | 0/30 [00:00<?, ?it/s]

Training CNN Model:   3%|▎         | 1/30 [01:53<54:47, 113.37s/it]

Epoch: 0 | Train Loss: 2.490404 | Train Accuracy: 19.70% |Test Loss: 2.014 | Test Accuracy: 19.62


Training CNN Model:  20%|██        | 6/30 [11:10<44:46, 111.95s/it]

Epoch: 5 | Train Loss: 1.113001 | Train Accuracy: 57.60% |Test Loss: 1.276 | Test Accuracy: 53.30


Training CNN Model:  37%|███▋      | 11/30 [20:31<35:39, 112.60s/it]

Epoch: 10 | Train Loss: 0.482347 | Train Accuracy: 82.99% |Test Loss: 0.690 | Test Accuracy: 78.12


Training CNN Model:  53%|█████▎    | 16/30 [30:06<26:49, 114.94s/it]

Epoch: 15 | Train Loss: 0.206388 | Train Accuracy: 93.49% |Test Loss: 0.620 | Test Accuracy: 84.90


Training CNN Model:  70%|███████   | 21/30 [38:42<15:04, 100.54s/it]

Epoch: 20 | Train Loss: 0.113810 | Train Accuracy: 95.96% |Test Loss: 0.679 | Test Accuracy: 87.50


Training CNN Model:  87%|████████▋ | 26/30 [46:10<06:07, 91.77s/it] 

Epoch: 25 | Train Loss: 0.074047 | Train Accuracy: 97.22% |Test Loss: 0.691 | Test Accuracy: 90.45


Training CNN Model: 100%|██████████| 30/30 [52:03<00:00, 104.12s/it]
